# utils/lang.py — all UI strings in one place
# To add a new language: copy the "en" block, change the key, translate values.

STRINGS = {
    "en": {
        # ── App ───────────────────────────────────────────────────────────────
        "app.title":              "Filegu",
        "app.subtitle":           "Search · Delete · Clean cache · Scan for threats",

        # ── Tabs ──────────────────────────────────────────────────────────────
        "tab.search":             "Search",
        "tab.cache":              "Cache Cleaner",
        "tab.virus":              "Virus Scanner",
        "tab.settings":           "Settings",

        # ── Search tab ────────────────────────────────────────────────────────
        "search.query_label":     "SEARCH QUERY",
        "search.match_label":     "MATCH MODE",
        "search.match_keyword":   "Keyword",
        "search.match_exact":     "Exact name",
        "search.match_hint":      "Keyword: 'disc' finds 'Discord'\nExact: 'discord' only finds 'discord'",
        "search.for_label":       "SEARCH FOR",
        "search.for_both":        "Files & folders",
        "search.for_files":       "Files only",
        "search.for_folders":     "Folders only",
        "search.in_label":        "SEARCH IN",
        "search.all_drives":      "All drives / entire system",
        "search.btn_search":      "Search",
        "search.btn_save":        "Save results",
        "search.btn_clear":       "Clear",
        "search.btn_delete":      "Delete selected",
        "search.btn_stop":        "Stop",
        "search.btn_browse":      "Browse",
        "search.status_ready":    "Ready — enter a keyword and press Search",
        "search.col_type":        "Type",
        "search.col_name":        "Name",
        "search.col_path":        "Full path",
        "search.col_size":        "Size",
        "search.status_complete": "Search complete",
        "search.status_stopped":  "Search stopped",
        "search.status_results":  "{n} result(s) found",
        "search.status_scanning": "Searching {n} location(s)…",
        "search.dirs_scanned":    "{n} dirs scanned",
        "search.no_keyword":      "Please enter at least one keyword.",
        "search.confirm_delete":  "Permanently delete this {kind}?\n\n{path}\n\nThis cannot be undone.",
        "search.perm_denied":     "Cannot delete:\n{path}",
        "search.already_gone":    "No longer exists:\n{path}",
        "search.saved":           "Results saved to:\n{path}",
        "search.took":            "took {t}",
        "search.elapsed_zero":    "0s",
        "search.type_file":       "📄 File",
        "search.type_folder":     "📁 Folder",
        "search.drive_progress":  "drive {i}/{n}",

        # ── Cache tab ─────────────────────────────────────────────────────────
        "cache.group_system":     "System",
        "cache.group_browsers":   "Browsers",
        "cache.group_dev":        "Dev",
        "cache.group_ides":       "IDEs",
        "cache.group_apps":       "Apps",
        "cache.group_games":      "Games",
        "cache.hint":             "Select what to clean, then press Scan to see sizes before deleting.",
        "cache.select_all":       "Select all",
        "cache.deselect_all":     "Deselect all",
        "cache.select":           "select",
        "cache.deselect":         "deselect",
        "cache.btn_scan":         "Scan sizes",
        "cache.btn_clean":        "Clean selected",
        "cache.scanning":         "Scanning {label}… ({i}/{n})",
        "cache.scan_complete":    "Scan complete",
        "cache.total":            "Total: {size}",
        "cache.cleaning":         "Cleaning…",
        "cache.done":             "All done!",
        "cache.done_errors":      "Done — {n} error(s)",
        "cache.freed":            "Freed: {size}",
        "cache.not_found":        "not found",
        "cache.cleaned":          "cleaned",
        "cache.nothing_selected": "Check at least one cache category to scan.",
        "cache.confirm_clean":    "Permanently delete cache for {n} selected {word}?\n\n{items}\n\nThis cannot be undone.",
        "cache.confirm_word_one": "category",
        "cache.confirm_word_many":"categories",
        "cache.errors_title":     "Some errors",
        "cache.errors_msg":       "{n} items could not be deleted:",


        # ── Cache item names ──────────────────────────────────────────────────
        "cache.item.win_temp":        "Windows Temp files",
        "cache.item.win_prefetch":    "Windows Prefetch",
        "cache.item.win_wer":         "Windows Error Reporting",
        "cache.item.win_update":      "Windows Update cache",
        "cache.item.win_delivery":    "Delivery Optimization",
        "cache.item.win_dx":          "DirectX Shader cache",
        "cache.item.win_recent":      "Recent files list",
        "cache.item.win_thumb":       "Thumbnail cache",
        "cache.item.win_fonts":       "Windows Font cache",
        "cache.item.win_events":      "Windows Event logs",
        "cache.item.win_defender":    "Windows Defender history",
        "cache.item.win_iis":         "IIS logs",
        "cache.item.chrome":          "Chrome cache",
        "cache.item.chrome_gpu":      "Chrome GPU cache",
        "cache.item.edge":            "Edge cache",
        "cache.item.edge_webview":    "Edge WebView2",
        "cache.item.firefox":         "Firefox cache",
        "cache.item.opera":           "Opera cache",
        "cache.item.brave":           "Brave cache",
        "cache.item.npm":             "npm cache",
        "cache.item.pip":             "pip cache",
        "cache.item.gradle":          "Gradle cache",
        "cache.item.gradle_wrapper":  "Gradle wrapper",
        "cache.item.maven":           "Maven cache",
        "cache.item.yarn":            "Yarn cache",
        "cache.item.pnpm":            "pnpm cache",
        "cache.item.pycache":         "__pycache__",
        "cache.item.mypy":            ".mypy_cache",
        "cache.item.cargo":           "Rust cargo cache",
        "cache.item.docker":          "Docker images",
        "cache.item.android":         "Android AVD cache",
        "cache.item.nuget":           "NuGet cache",
        "cache.item.composer":        "Composer cache",
        "cache.item.dotnet":          "dotnet temp",
        "cache.item.nextjs":          "Next.js cache",
        "cache.item.parcel":          "Parcel cache",
        "cache.item.webpack":         "Webpack/Vite cache",
        "cache.item.jetbrains":       "JetBrains system cache",
        "cache.item.vscode_ws":       "VS Code workspace cache",
        "cache.item.vscode_ext":      "VS Code extension cache",
        "cache.item.spotify":         "Spotify cache",
        "cache.item.discord":         "Discord cache",
        "cache.item.teams":           "Teams cache",
        "cache.item.zoom":            "Zoom cache",
        "cache.item.slack":           "Slack cache",
        "cache.item.telegram":        "Telegram cache",
        "cache.item.whatsapp":        "WhatsApp cache",
        "cache.item.steam_shader":    "Steam shader cache",
        "cache.item.epic":            "Epic Games cache",
        "cache.item.gog":             "GOG Galaxy cache",
        "cache.item.riot":            "Riot Games cache",

        # ── Cache item descriptions ────────────────────────────────────────────
        "cache.desc.win_temp":        "Temporary files created by Windows and apps",
        "cache.desc.win_prefetch":    "App launch cache — speeds up startup but can grow large",
        "cache.desc.win_wer":         "Crash dump files — can be several GB",
        "cache.desc.win_update":      "Downloaded Windows updates already installed — safe to clear",
        "cache.desc.win_delivery":    "P2P Windows Update delivery cache (requires admin)",
        "cache.desc.win_dx":          "GPU shader compilation cache — rebuilt automatically",
        "cache.desc.win_recent":      "Jump list / recently opened files shortcuts",
        "cache.desc.win_thumb":       "Explorer thumbnail previews",
        "cache.desc.win_fonts":       "Windows font cache — rebuilt automatically",
        "cache.desc.win_events":      "System event log files (requires admin)",
        "cache.desc.win_defender":    "Windows Defender scan history",
        "cache.desc.win_iis":         "IIS web server logs (only if IIS is installed)",
        "cache.desc.chrome":          "HTTP cache + JS code cache for Google Chrome",
        "cache.desc.chrome_gpu":      "GPU shader cache for Chrome — rebuilt automatically",
        "cache.desc.edge":            "HTTP cache for Microsoft Edge",
        "cache.desc.edge_webview":    "Embedded browser cache used by many Windows apps",
        "cache.desc.firefox":         "HTTP cache for all Firefox profiles",
        "cache.desc.opera":           "HTTP cache for Opera",
        "cache.desc.brave":           "HTTP cache for Brave Browser",
        "cache.desc.npm":             "npm package cache (~/.npm)",
        "cache.desc.pip":             "pip wheel/package cache",
        "cache.desc.gradle":          "Gradle build cache",
        "cache.desc.gradle_wrapper":  "Downloaded Gradle distributions — can be several GB",
        "cache.desc.maven":           "Maven local repository (~/.m2)",
        "cache.desc.yarn":            "Yarn package cache",
        "cache.desc.pnpm":            "pnpm content-addressable store",
        "cache.desc.pycache":         "Python bytecode cache dirs (scanned from home)",
        "cache.desc.mypy":            "mypy type-check cache dirs",
        "cache.desc.cargo":           "Cargo downloaded crate cache",
        "cache.desc.docker":          "Docker image layer cache — can be many GB",
        "cache.desc.android":         "Android emulator snapshots",
        "cache.desc.nuget":           "NuGet package cache — can be 10 GB+",
        "cache.desc.composer":        "PHP Composer package cache",
        "cache.desc.dotnet":          ".NET SDK temp files and tools",
        "cache.desc.nextjs":          ".next/cache dirs (scanned from home)",
        "cache.desc.parcel":          ".parcel-cache dirs (scanned from home)",
        "cache.desc.webpack":         "node_modules/.cache and .vite dirs (scanned from home)",
        "cache.desc.jetbrains":       "IntelliJ / PyCharm / WebStorm etc. caches",
        "cache.desc.vscode_ws":       "Per-workspace extension data & cache",
        "cache.desc.vscode_ext":      "Cached extension VSIX downloads",
        "cache.desc.spotify":         "Spotify audio/image cache — can be several GB",
        "cache.desc.discord":         "Discord media cache",
        "cache.desc.teams":           "Microsoft Teams HTTP cache and blob storage",
        "cache.desc.zoom":            "Zoom meeting data cache",
        "cache.desc.slack":           "Slack media and message cache",
        "cache.desc.telegram":        "Telegram Desktop cached media",
        "cache.desc.whatsapp":        "WhatsApp Desktop cache",
        "cache.desc.steam_shader":    "Compiled GPU shaders for Steam games — rebuilt on demand",
        "cache.desc.epic":            "Epic Games Launcher web cache",
        "cache.desc.gog":             "GOG Galaxy Launcher web cache",
        "cache.desc.riot":            "Riot Client cache (League, Valorant etc.)",
        # ── Virus Scanner tab ─────────────────────────────────────────────────
        "virus.scan_in":          "SCAN IN",
        "virus.all_drives":       "All drives",
        "virus.single_file":      "OR SINGLE FILE",
        "virus.btn_browse":       "Browse file…",
        "virus.btn_start":        "Start Scan",
        "virus.btn_stop":         "Stop",
        "virus.btn_save":         "Save report",
        "virus.btn_clear":        "Clear",
        "virus.btn_deepscan":     "Deep Scan flagged",
        "virus.auto_deepscan":    "Auto deep scan after scan",
        "virus.auto_vt":          "Include VirusTotal check",
        "virus.auto_vt_hint":     "May take extra time.",
        "virus.auto_vt_no_key":   "VirusTotal API key is required for automatic online verification.\n\nPlease enter your key in the Online tab first.",
        "virus.btn_verify":       "Verify online (VirusTotal)",
        "virus.tab_malicious":    "Malicious",
        "virus.tab_suspicious":   "Suspicious",
        "virus.tab_online":       "Online",
        "virus.clean_count":      "Clean: {n}",
        "virus.status_ready":     "Select drives or a file, then press Start Scan.",
        "virus.status_finding":   "Finding files…",
        "virus.status_scanning":  "Scanning {n:,} file(s)…",
        "virus.status_complete":  "Scan complete — {scanned:,} scanned · {mal} malicious · {susp} suspicious",
        "virus.status_stopped":   "Scan stopped — {scanned:,} scanned",
        "virus.status_threat":    "{name} confirmed malicious by {n} engines!",
        "virus.col_file":         "File",
        "virus.col_score":        "Score",
        "virus.col_finding":      "Top finding",
        "virus.col_entropy":      "Entropy",
        "virus.col_verdict":      "VT Verdict",
        "virus.col_detections":   "Detections",
        "virus.col_engines":      "Engines",
        "virus.col_threat":       "Threat name",
        "virus.vt_api_label":     "VirusTotal API key:",
        "virus.vt_api_hint":      "Free key at virustotal.com · 4 req/min on free tier",
        "virus.vt_show":          "Show",
        "virus.vt_hide":          "Hide",
        "virus.vt_status_ready":  "Enter your API key and click Verify Online.",
        "virus.vt_complete":      "Online verification complete — {n} file(s) checked",
        "virus.vt_waiting":       "Waiting {s}s (free tier limit)… {done}/{total} done",
        "virus.vt_no_key":        "Enter your VirusTotal API key in the Online tab.",
        "virus.vt_nothing":       "No flagged files with computed hashes. Run a normal scan first.",
        "virus.vt_not_in_db":     "Not in DB",
        "virus.vt_error":         "Error",
        "virus.deepscan_confirm": "Run deep scan on {n} flagged file(s)?\n\nClean files will be removed from results.\nEach flagged file will be re-scanned with full entropy,\nstring extraction, PE section analysis and more.",
        "virus.no_key":           "No API key",
        "virus.nothing_to_scan":  "No files matched the selected filters.",
        "virus.nothing_selected": "Select at least one drive, or browse to a single file.",
        "virus.delete_file":      "Permanently delete:\n{path}\n\nThis cannot be undone.",
        "virus.detail_hash":      "SHA-256:  {v}",
        "virus.detail_size":      "Size:     {v} bytes",
        "virus.detail_entropy":   "Entropy:  {v} ({label})",
        "virus.detail_hashdb":    "Hash DB:  {v}",
        "virus.detail_hashdb_hit":"YES — known malware",
        "virus.detail_hashdb_no": "No match",
        "virus.detail_sig":       "Signature: {status}{signer}",
        "virus.detail_findings":  "── FINDINGS ─────────────────────────────────────────────",
        "virus.detail_yara":      "── YARA MATCHES ──────────────────────────────────────────",
        "virus.detail_sections":  "── PE SECTIONS ───────────────────────────────────────────",
        "virus.detail_open":      "Open file location",
        "virus.took":             "⏱ took {t}",
        "virus.stopped_at":       "⏱ stopped at {t}",
        "virus.elapsed":          "⏱ {t}",
        "virus.time_s":           "s",
        "virus.time_m":           "m",
        "virus.time_h":           "h",
        "virus.status_complete_word": "Scan complete",
        "virus.status_stopped_word":  "Scan stopped",
        "virus.word_scanned":     "scanned",
        "virus.word_malicious":   "malicious",
        "virus.word_suspicious":  "suspicious",
        "virus.word_processed":   "processed",

        # ── Settings tab ──────────────────────────────────────────────────────
        "settings.section_virus":    "VIRUS SCANNER",
        "settings.section_search":   "SEARCH",
        "settings.section_ui":       "INTERFACE",
        "settings.threads":          "Threads",
        "settings.threads_desc":     "How many files to scan in parallel. Higher = faster, uses more CPU.",
        "settings.skip_media":       "Skip media & font files",
        "settings.skip_media_desc":  "Skip .jpg, .png, .mp4, .ttf etc.",
        "settings.exe_only":         "Executables & scripts only",
        "settings.exe_only_desc":    "Only scan .exe, .dll, .bat, .ps1, .js etc.",
        "settings.vt_key":           "VirusTotal API key",
        "settings.vt_key_desc":      "Used for online verification. Free key at virustotal.com",
        "settings.extra_ext":        "Extra extensions to skip",
        "settings.extra_ext_desc":   "One per line, with dot.  e.g.  .crp  .pak",
        "settings.extra_dirs":       "Extra folders to skip",
        "settings.extra_dirs_desc":  "Folder names to skip.  e.g.  Steam  Games",
        "settings.default_mode":     "Default match mode",
        "settings.default_mode_desc":"",
        "settings.keyword":          "Keyword (partial match)",
        "settings.exact":            "Exact name",
        "settings.default_type":     "Default search for",
        "settings.default_type_desc":"",
        "settings.default_tab":      "Default tab on startup",
        "settings.default_tab_desc": "",
        "settings.language":         "Language",
        "settings.language_desc":    "App language. Restart required to apply.",
        "settings.btn_save":         "Save settings",
        "settings.btn_reset":        "Reset to defaults",
        "settings.saved":            "✓ Saved — restart to apply language changes",
        "settings.saved_no_restart": "✓ Saved",
        "settings.reset_confirm":    "Reset all settings to defaults?",
        "settings.reset_done":       "✓ Reset to defaults",
        "settings.save_failed":      "Could not write config.json — check file permissions.",

        # ── Common ────────────────────────────────────────────────────────────
        "common.ok":              "OK",
        "common.yes":             "Yes",
        "common.no":              "No",
        "common.cancel":          "Cancel",
        "common.error":           "Error",
        "common.warning":         "Warning",
        "common.saved":           "Saved",
        "common.confirm_delete":  "Confirm delete",
        "common.perm_denied":     "Permission denied",
        "common.already_gone":    "Already gone",
        "common.open_location":   "Open location",
        "common.copy_path":       "Copy path",
        "common.copy_name":       "Copy name",
        "common.delete":          "Delete this item",
        "common.folder":          "folder and ALL its contents",
        "common.file":            "file",
        "common.not_responding":  "Not responding",
    },

    "ru": {
        # ── App ───────────────────────────────────────────────────────────────
        "app.title":              "Filegu",
        "app.subtitle":           "Поиск · Удаление · Очистка кэша · Сканирование угроз",

        # ── Tabs ──────────────────────────────────────────────────────────────
        "tab.search":             "Поиск",
        "tab.cache":              "Очистка кэша",
        "tab.virus":              "Антивирус",
        "tab.settings":           "Настройки",

        # ── Search tab ────────────────────────────────────────────────────────
        "search.query_label":     "ПОИСКОВЫЙ ЗАПРОС",
        "search.match_label":     "РЕЖИМ ПОИСКА",
        "search.match_keyword":   "По ключевому слову",
        "search.match_exact":     "Точное совпадение",
        "search.match_hint":      "По слову: 'disc' найдёт 'Discord'\nТочное: 'discord' найдёт только 'discord'",
        "search.for_label":       "ЧТО ИСКАТЬ",
        "search.for_both":        "Файлы и папки",
        "search.for_files":       "Только файлы",
        "search.for_folders":     "Только папки",
        "search.in_label":        "ГДЕ ИСКАТЬ",
        "search.all_drives":      "Все диски / вся система",
        "search.btn_search":      "Найти",
        "search.btn_save":        "Сохранить результаты",
        "search.btn_clear":       "Очистить",
        "search.btn_delete":      "Удалить выбранное",
        "search.btn_stop":        "Стоп",
        "search.btn_browse":      "Обзор",
        "search.status_ready":    "Готово — введите запрос и нажмите Найти",
        "search.col_type":        "Тип",
        "search.col_name":        "Имя",
        "search.col_path":        "Полный путь",
        "search.col_size":        "Размер",
        "search.status_complete": "Поиск завершён",
        "search.status_stopped":  "Поиск остановлен",
        "search.status_results":  "Найдено: {n}",
        "search.status_scanning": "Поиск в {n} местах…",
        "search.dirs_scanned":    "Просмотрено папок: {n}",
        "search.no_keyword":      "Введите хотя бы одно ключевое слово.",
        "search.confirm_delete":  "Удалить навсегда {kind}?\n\n{path}\n\nОтменить это действие нельзя.",
        "search.perm_denied":     "Нет доступа:\n{path}",
        "search.already_gone":    "Уже не существует:\n{path}",
        "search.saved":           "Результаты сохранены в:\n{path}",
        "search.took":            "заняло {t}",
        "search.elapsed_zero":    "0с",
        "search.type_file":       "📄 Файл",
        "search.type_folder":     "📁 Папка",
        "search.drive_progress":  "диск {i}/{n}",

        # ── Cache tab ─────────────────────────────────────────────────────────
        "cache.group_system":     "Система",
        "cache.group_browsers":   "Браузеры",
        "cache.group_dev":        "Разработка",
        "cache.group_ides":       "IDE",
        "cache.group_apps":       "Приложения",
        "cache.group_games":      "Игры",
        "cache.hint":             "Выберите категории, затем нажмите Сканировать для просмотра размеров.",
        "cache.select_all":       "Выбрать всё",
        "cache.deselect_all":     "Снять всё",
        "cache.select":           "выбрать",
        "cache.deselect":         "снять",
        "cache.btn_scan":         "Сканировать",
        "cache.btn_clean":        "Очистить выбранное",
        "cache.scanning":         "Сканирование {label}… ({i}/{n})",
        "cache.scan_complete":    "Сканирование завершено",
        "cache.total":            "Итого: {size}",
        "cache.cleaning":         "Очистка…",
        "cache.done":             "Готово!",
        "cache.done_errors":      "Готово — ошибок: {n}",
        "cache.freed":            "Освобождено: {size}",
        "cache.not_found":        "не найдено",
        "cache.cleaned":          "очищено",
        "cache.nothing_selected": "Выберите хотя бы одну категорию кэша.",
        "cache.confirm_clean":    "Удалить кэш для {n} выбранных {word}?\n\n{items}\n\nОтменить это действие нельзя.",
        "cache.confirm_word_one": "категории",
        "cache.confirm_word_many":"категорий",
        "cache.errors_title":     "Ошибки",
        "cache.errors_msg":       "Не удалось удалить {n} элементов:",


        # ── Cache item names ──────────────────────────────────────────────────
        "cache.item.win_temp":        "Временные файлы Windows",
        "cache.item.win_prefetch":    "Windows Prefetch",
        "cache.item.win_wer":         "Отчёты об ошибках Windows",
        "cache.item.win_update":      "Кэш обновлений Windows",
        "cache.item.win_delivery":    "Оптимизация доставки",
        "cache.item.win_dx":          "Кэш шейдеров DirectX",
        "cache.item.win_recent":      "Список последних файлов",
        "cache.item.win_thumb":       "Кэш эскизов",
        "cache.item.win_fonts":       "Кэш шрифтов Windows",
        "cache.item.win_events":      "Журналы событий Windows",
        "cache.item.win_defender":    "История Windows Defender",
        "cache.item.win_iis":         "Журналы IIS",
        "cache.item.chrome":          "Кэш Chrome",
        "cache.item.chrome_gpu":      "GPU кэш Chrome",
        "cache.item.edge":            "Кэш Edge",
        "cache.item.edge_webview":    "Edge WebView2",
        "cache.item.firefox":         "Кэш Firefox",
        "cache.item.opera":           "Кэш Opera",
        "cache.item.brave":           "Кэш Brave",
        "cache.item.npm":             "Кэш npm",
        "cache.item.pip":             "Кэш pip",
        "cache.item.gradle":          "Кэш Gradle",
        "cache.item.gradle_wrapper":  "Дистрибутивы Gradle",
        "cache.item.maven":           "Кэш Maven",
        "cache.item.yarn":            "Кэш Yarn",
        "cache.item.pnpm":            "Кэш pnpm",
        "cache.item.pycache":         "__pycache__",
        "cache.item.mypy":            ".mypy_cache",
        "cache.item.cargo":           "Кэш Rust/Cargo",
        "cache.item.docker":          "Образы Docker",
        "cache.item.android":         "Кэш Android AVD",
        "cache.item.nuget":           "Кэш NuGet",
        "cache.item.composer":        "Кэш Composer",
        "cache.item.dotnet":          "Временные файлы .NET",
        "cache.item.nextjs":          "Кэш Next.js",
        "cache.item.parcel":          "Кэш Parcel",
        "cache.item.webpack":         "Кэш Webpack/Vite",
        "cache.item.jetbrains":       "Кэш JetBrains",
        "cache.item.vscode_ws":       "Рабочие области VS Code",
        "cache.item.vscode_ext":      "Кэш расширений VS Code",
        "cache.item.spotify":         "Кэш Spotify",
        "cache.item.discord":         "Кэш Discord",
        "cache.item.teams":           "Кэш Teams",
        "cache.item.zoom":            "Кэш Zoom",
        "cache.item.slack":           "Кэш Slack",
        "cache.item.telegram":        "Кэш Telegram",
        "cache.item.whatsapp":        "Кэш WhatsApp",
        "cache.item.steam_shader":    "Кэш шейдеров Steam",
        "cache.item.epic":            "Кэш Epic Games",
        "cache.item.gog":             "Кэш GOG Galaxy",
        "cache.item.riot":            "Кэш Riot Games",

        # ── Cache item descriptions ────────────────────────────────────────────
        "cache.desc.win_temp":        "Временные файлы Windows и приложений",
        "cache.desc.win_prefetch":    "Кэш запуска приложений — ускоряет старт, но может разрастаться",
        "cache.desc.win_wer":         "Файлы аварийных дампов — может занимать несколько ГБ",
        "cache.desc.win_update":      "Загруженные обновления Windows, уже установленные — безопасно удалять",
        "cache.desc.win_delivery":    "Кэш P2P-доставки обновлений Windows (требуются права администратора)",
        "cache.desc.win_dx":          "Кэш компиляции шейдеров GPU — восстанавливается автоматически",
        "cache.desc.win_recent":      "Список переходов / ярлыки недавно открытых файлов",
        "cache.desc.win_thumb":       "Превью эскизов в Проводнике",
        "cache.desc.win_fonts":       "Кэш шрифтов Windows — восстанавливается автоматически",
        "cache.desc.win_events":      "Файлы системных журналов (требуются права администратора)",
        "cache.desc.win_defender":    "История сканирования Windows Defender",
        "cache.desc.win_iis":         "Журналы веб-сервера IIS (только если IIS установлен)",
        "cache.desc.chrome":          "HTTP-кэш + кэш JS-кода Google Chrome",
        "cache.desc.chrome_gpu":      "Кэш шейдеров GPU Chrome — восстанавливается автоматически",
        "cache.desc.edge":            "HTTP-кэш Microsoft Edge",
        "cache.desc.edge_webview":    "Встроенный браузерный кэш, используемый многими приложениями Windows",
        "cache.desc.firefox":         "HTTP-кэш всех профилей Firefox",
        "cache.desc.opera":           "HTTP-кэш Opera",
        "cache.desc.brave":           "HTTP-кэш Brave Browser",
        "cache.desc.npm":             "Кэш пакетов npm (~/.npm)",
        "cache.desc.pip":             "Кэш пакетов pip",
        "cache.desc.gradle":          "Кэш сборки Gradle",
        "cache.desc.gradle_wrapper":  "Загруженные дистрибутивы Gradle — может занимать несколько ГБ",
        "cache.desc.maven":           "Локальный репозиторий Maven (~/.m2)",
        "cache.desc.yarn":            "Кэш пакетов Yarn",
        "cache.desc.pnpm":            "Хранилище pnpm",
        "cache.desc.pycache":         "Папки кэша байткода Python (сканируется из домашней папки)",
        "cache.desc.mypy":            "Папки кэша проверки типов mypy",
        "cache.desc.cargo":           "Кэш загруженных крейтов Cargo",
        "cache.desc.docker":          "Кэш слоёв образов Docker — может занимать много ГБ",
        "cache.desc.android":         "Снимки состояния эмулятора Android",
        "cache.desc.nuget":           "Кэш пакетов NuGet — может занимать 10 ГБ+",
        "cache.desc.composer":        "Кэш пакетов PHP Composer",
        "cache.desc.dotnet":          "Временные файлы и инструменты .NET SDK",
        "cache.desc.nextjs":          "Папки .next/cache (сканируется из домашней папки)",
        "cache.desc.parcel":          "Папки .parcel-cache (сканируется из домашней папки)",
        "cache.desc.webpack":         "Папки node_modules/.cache и .vite (сканируется из домашней папки)",
        "cache.desc.jetbrains":       "Кэш IntelliJ / PyCharm / WebStorm и др.",
        "cache.desc.vscode_ws":       "Данные расширений и кэш рабочих областей VS Code",
        "cache.desc.vscode_ext":      "Загруженные VSIX-файлы расширений VS Code",
        "cache.desc.spotify":         "Кэш аудио/изображений Spotify — может занимать несколько ГБ",
        "cache.desc.discord":         "Медиакэш Discord",
        "cache.desc.teams":           "HTTP-кэш и хранилище blob Microsoft Teams",
        "cache.desc.zoom":            "Кэш данных встреч Zoom",
        "cache.desc.slack":           "Кэш медиа и сообщений Slack",
        "cache.desc.telegram":        "Кэш медиафайлов Telegram Desktop",
        "cache.desc.whatsapp":        "Кэш WhatsApp Desktop",
        "cache.desc.steam_shader":    "Скомпилированные шейдеры GPU для игр Steam — восстанавливаются по запросу",
        "cache.desc.epic":            "Веб-кэш Epic Games Launcher",
        "cache.desc.gog":             "Веб-кэш GOG Galaxy Launcher",
        "cache.desc.riot":            "Кэш Riot Client (League, Valorant и др.)",
        # ── Virus Scanner tab ─────────────────────────────────────────────────
        "virus.scan_in":          "СКАНИРОВАТЬ",
        "virus.all_drives":       "Все диски",
        "virus.single_file":      "ИЛИ ОДИН ФАЙЛ",
        "virus.btn_browse":       "Выбрать файл…",
        "virus.btn_start":        "Начать сканирование",
        "virus.btn_stop":         "Стоп",
        "virus.btn_save":         "Сохранить отчёт",
        "virus.btn_clear":        "Очистить",
        "virus.btn_deepscan":     "Глубокое сканирование",
        "virus.auto_deepscan":    "Авто глубокое сканирование",
        "virus.auto_vt":          "Включить проверку VirusTotal",
        "virus.auto_vt_hint":     "Может занять дополнительное время.",
        "virus.auto_vt_no_key":   "Для автоматической онлайн-проверки требуется API-ключ VirusTotal.\n\nПожалуйста, введите ключ на вкладке Онлайн.",
        "virus.btn_verify":       "Проверить онлайн (VirusTotal)",
        "virus.tab_malicious":    "Угрозы",
        "virus.tab_suspicious":   "Подозрительные",
        "virus.tab_online":       "Онлайн",
        "virus.clean_count":      "Чистых: {n}",
        "virus.status_ready":     "Выберите диски или файл и нажмите Начать сканирование.",
        "virus.status_finding":   "Поиск файлов…",
        "virus.status_scanning":  "Сканирование {n:,} файл(ов)…",
        "virus.status_complete":  "Сканирование завершено — {scanned:,} проверено · {mal} угроз · {susp} подозрительных",
        "virus.status_stopped":   "Сканирование остановлено — {scanned:,} проверено",
        "virus.status_threat":    "{name} подтверждён вредоносным {n} антивирусами!",
        "virus.col_file":         "Файл",
        "virus.col_score":        "Оценка",
        "virus.col_finding":      "Основная угроза",
        "virus.col_entropy":      "Энтропия",
        "virus.col_verdict":      "Вердикт VT",
        "virus.col_detections":   "Обнаружений",
        "virus.col_engines":      "Движков",
        "virus.col_threat":       "Название угрозы",
        "virus.vt_api_label":     "API ключ VirusTotal:",
        "virus.vt_api_hint":      "Бесплатный ключ на virustotal.com · 4 запроса/мин",
        "virus.vt_show":          "Показать",
        "virus.vt_hide":          "Скрыть",
        "virus.vt_status_ready":  "Введите API ключ и нажмите Проверить онлайн.",
        "virus.vt_complete":      "Онлайн-проверка завершена — проверено файлов: {n}",
        "virus.vt_waiting":       "Ожидание {s}с (лимит бесплатного тарифа)… {done}/{total} готово",
        "virus.vt_no_key":        "Введите API ключ VirusTotal на вкладке Онлайн.",
        "virus.vt_nothing":       "Нет помеченных файлов с вычисленными хэшами. Сначала выполните сканирование.",
        "virus.vt_not_in_db":     "Нет в базе",
        "virus.vt_error":         "Ошибка",
        "virus.deepscan_confirm": "Запустить глубокое сканирование {n} помеченных файлов?\n\nЧистые файлы будут удалены из результатов.\nКаждый файл будет повторно проверен с полным анализом энтропии,\nизвлечением строк, анализом PE-секций и другими методами.",
        "virus.no_key":           "Нет API ключа",
        "virus.nothing_to_scan":  "Файлы не найдены по выбранным фильтрам.",
        "virus.nothing_selected": "Выберите хотя бы один диск или укажите файл.",
        "virus.delete_file":      "Удалить навсегда:\n{path}\n\nОтменить это действие нельзя.",
        "virus.detail_hash":      "SHA-256:   {v}",
        "virus.detail_size":      "Размер:    {v} байт",
        "virus.detail_entropy":   "Энтропия:  {v} ({label})",
        "virus.detail_hashdb":    "База хэшей: {v}",
        "virus.detail_hashdb_hit":"ДА — известная угроза",
        "virus.detail_hashdb_no": "Не найдено",
        "virus.detail_sig":       "Подпись: {status}{signer}",
        "virus.detail_findings":  "── ОБНАРУЖЕНИЯ ──────────────────────────────────────────",
        "virus.detail_yara":      "── СОВПАДЕНИЯ YARA ──────────────────────────────────────",
        "virus.detail_sections":  "── PE-СЕКЦИИ ────────────────────────────────────────────",
        "virus.detail_open":      "Открыть расположение",
        "virus.took":             "⏱ заняло {t}",
        "virus.stopped_at":       "⏱ остановлено на {t}",
        "virus.elapsed":          "⏱ {t}",
        "virus.time_s":           "с",
        "virus.time_m":           "м",
        "virus.time_h":           "ч",
        "virus.status_complete_word": "Сканирование завершено",
        "virus.status_stopped_word":  "Сканирование остановлено",
        "virus.word_scanned":     "проверено",
        "virus.word_malicious":   "угроз",
        "virus.word_suspicious":  "подозрительных",
        "virus.word_processed":   "обработано",

        # ── Settings tab ──────────────────────────────────────────────────────
        "settings.section_virus":    "АНТИВИРУС",
        "settings.section_search":   "ПОИСК",
        "settings.section_ui":       "ИНТЕРФЕЙС",
        "settings.threads":          "Потоки",
        "settings.threads_desc":     "Количество файлов для параллельного сканирования. Больше = быстрее, но нагружает CPU.",
        "settings.skip_media":       "Пропускать медиа и шрифты",
        "settings.skip_media_desc":  "Пропускать .jpg, .png, .mp4, .ttf и т.д.",
        "settings.exe_only":         "Только исполняемые файлы и скрипты",
        "settings.exe_only_desc":    "Сканировать только .exe, .dll, .bat, .ps1, .js и т.д.",
        "settings.vt_key":           "API ключ VirusTotal",
        "settings.vt_key_desc":      "Для онлайн-проверки. Бесплатный ключ на virustotal.com",
        "settings.extra_ext":        "Дополнительные расширения для пропуска",
        "settings.extra_ext_desc":   "По одному на строку, с точкой.  Пример: .crp  .pak",
        "settings.extra_dirs":       "Дополнительные папки для пропуска",
        "settings.extra_dirs_desc":  "Имена папок для пропуска.  Пример: Steam  Games",
        "settings.default_mode":     "Режим поиска по умолчанию",
        "settings.default_mode_desc":"",
        "settings.keyword":          "По ключевому слову",
        "settings.exact":            "Точное совпадение",
        "settings.default_type":     "Что искать по умолчанию",
        "settings.default_type_desc":"",
        "settings.default_tab":      "Вкладка при запуске",
        "settings.default_tab_desc": "",
        "settings.language":         "Язык",
        "settings.language_desc":    "Язык интерфейса. Требуется перезапуск.",
        "settings.btn_save":         "Сохранить настройки",
        "settings.btn_reset":        "Сбросить настройки",
        "settings.saved":            "✓ Сохранено — перезапустите для смены языка",
        "settings.saved_no_restart": "✓ Сохранено",
        "settings.reset_confirm":    "Сбросить все настройки до значений по умолчанию?",
        "settings.reset_done":       "✓ Настройки сброшены",
        "settings.save_failed":      "Не удалось записать config.json — проверьте права доступа.",

        # ── Common ────────────────────────────────────────────────────────────
        "common.ok":              "ОК",
        "common.yes":             "Да",
        "common.no":              "Нет",
        "common.cancel":          "Отмена",
        "common.error":           "Ошибка",
        "common.warning":         "Предупреждение",
        "common.saved":           "Сохранено",
        "common.confirm_delete":  "Подтвердить удаление",
        "common.perm_denied":     "Нет доступа",
        "common.already_gone":    "Уже удалено",
        "common.open_location":   "Открыть расположение",
        "common.copy_path":       "Копировать путь",
        "common.copy_name":       "Копировать имя",
        "common.delete":          "Удалить",
        "common.folder":          "папку и ВСЁ её содержимое",
        "common.file":            "файл",
        "common.not_responding":  "Не отвечает",
    },

    "de": {
        # ── App ───────────────────────────────────────────────────────────────
        "app.title":              "Filegu",
        "app.subtitle":           "Suchen · Löschen · Cache leeren · Bedrohungen scannen",

        # ── Tabs ──────────────────────────────────────────────────────────────
        "tab.search":             "Suche",
        "tab.cache":              "Cache-Bereinigung",
        "tab.virus":              "Virenschutz",
        "tab.settings":           "Einstellungen",

        # ── Search tab ────────────────────────────────────────────────────────
        "search.query_label":     "SUCHBEGRIFF",
        "search.match_label":     "SUCHMODUS",
        "search.match_keyword":   "Stichwort",
        "search.match_exact":     "Exakter Name",
        "search.match_hint":      "Stichwort: 'disc' findet 'Discord'\nExakt: 'discord' findet nur 'discord'",
        "search.for_label":       "SUCHEN NACH",
        "search.for_both":        "Dateien & Ordner",
        "search.for_files":       "Nur Dateien",
        "search.for_folders":     "Nur Ordner",
        "search.in_label":        "SUCHEN IN",
        "search.all_drives":      "Alle Laufwerke / gesamtes System",
        "search.btn_search":      "Suchen",
        "search.btn_save":        "Ergebnisse speichern",
        "search.btn_clear":       "Leeren",
        "search.btn_delete":      "Auswahl löschen",
        "search.btn_stop":        "Stopp",
        "search.btn_browse":      "Durchsuchen",
        "search.status_ready":    "Bereit — Suchbegriff eingeben und Suchen drücken",
        "search.col_type":        "Typ",
        "search.col_name":        "Name",
        "search.col_path":        "Vollständiger Pfad",
        "search.col_size":        "Größe",
        "search.status_complete": "Suche abgeschlossen",
        "search.status_stopped":  "Suche gestoppt",
        "search.status_results":  "{n} Ergebnis(se) gefunden",
        "search.status_scanning": "Suche in {n} Ort(en)…",
        "search.dirs_scanned":    "{n} Ordner durchsucht",
        "search.no_keyword":      "Bitte mindestens einen Suchbegriff eingeben.",
        "search.confirm_delete":  "Diesen {kind} dauerhaft löschen?\n\n{path}\n\nDies kann nicht rückgängig gemacht werden.",
        "search.perm_denied":     "Kann nicht gelöscht werden:\n{path}",
        "search.already_gone":    "Existiert nicht mehr:\n{path}",
        "search.saved":           "Ergebnisse gespeichert in:\n{path}",
        "search.took":            "Dauer: {t}",
        "search.elapsed_zero":    "0s",
        "search.type_file":       "📄 Datei",
        "search.type_folder":     "📁 Ordner",
        "search.drive_progress":  "Laufwerk {i}/{n}",

        # ── Cache tab ─────────────────────────────────────────────────────────
        "cache.group_system":     "System",
        "cache.group_browsers":   "Browser",
        "cache.group_dev":        "Entwicklung",
        "cache.group_ides":       "IDEs",
        "cache.group_apps":       "Apps",
        "cache.group_games":      "Spiele",
        "cache.hint":             "Kategorien auswählen, dann Scannen drücken um Größen anzuzeigen.",
        "cache.select_all":       "Alle auswählen",
        "cache.deselect_all":     "Alle abwählen",
        "cache.select":           "wählen",
        "cache.deselect":         "abwählen",
        "cache.btn_scan":         "Größen scannen",
        "cache.btn_clean":        "Auswahl bereinigen",
        "cache.scanning":         "Scanne {label}… ({i}/{n})",
        "cache.scan_complete":    "Scan abgeschlossen",
        "cache.total":            "Gesamt: {size}",
        "cache.cleaning":         "Bereinigung…",
        "cache.done":             "Fertig!",
        "cache.done_errors":      "Fertig — {n} Fehler",
        "cache.freed":            "Freigegeben: {size}",
        "cache.not_found":        "nicht gefunden",
        "cache.cleaned":          "bereinigt",
        "cache.nothing_selected": "Bitte mindestens eine Cache-Kategorie auswählen.",
        "cache.confirm_clean":    "Cache für {n} ausgewählte {word} dauerhaft löschen?\n\n{items}\n\nDies kann nicht rückgängig gemacht werden.",
        "cache.confirm_word_one": "Kategorie",
        "cache.confirm_word_many":"Kategorien",
        "cache.errors_title":     "Einige Fehler",
        "cache.errors_msg":       "{n} Elemente konnten nicht gelöscht werden:",

        # ── Cache item names ──────────────────────────────────────────────────
        "cache.item.win_temp":        "Windows Temp-Dateien",
        "cache.item.win_prefetch":    "Windows Prefetch",
        "cache.item.win_wer":         "Windows-Fehlerberichte",
        "cache.item.win_update":      "Windows-Update-Cache",
        "cache.item.win_delivery":    "Übermittlungsoptimierung",
        "cache.item.win_dx":          "DirectX-Shader-Cache",
        "cache.item.win_recent":      "Zuletzt verwendete Dateien",
        "cache.item.win_thumb":       "Miniaturansichten-Cache",
        "cache.item.win_fonts":       "Windows-Schriftarten-Cache",
        "cache.item.win_events":      "Windows-Ereignisprotokolle",
        "cache.item.win_defender":    "Windows Defender-Verlauf",
        "cache.item.win_iis":         "IIS-Protokolle",
        "cache.item.chrome":          "Chrome-Cache",
        "cache.item.chrome_gpu":      "Chrome GPU-Cache",
        "cache.item.edge":            "Edge-Cache",
        "cache.item.edge_webview":    "Edge WebView2",
        "cache.item.firefox":         "Firefox-Cache",
        "cache.item.opera":           "Opera-Cache",
        "cache.item.brave":           "Brave-Cache",
        "cache.item.npm":             "npm-Cache",
        "cache.item.pip":             "pip-Cache",
        "cache.item.gradle":          "Gradle-Cache",
        "cache.item.gradle_wrapper":  "Gradle Wrapper",
        "cache.item.maven":           "Maven-Cache",
        "cache.item.yarn":            "Yarn-Cache",
        "cache.item.pnpm":            "pnpm-Cache",
        "cache.item.pycache":         "__pycache__",
        "cache.item.mypy":            ".mypy_cache",
        "cache.item.cargo":           "Rust Cargo-Cache",
        "cache.item.docker":          "Docker-Images",
        "cache.item.android":         "Android AVD-Cache",
        "cache.item.nuget":           "NuGet-Cache",
        "cache.item.composer":        "Composer-Cache",
        "cache.item.dotnet":          "dotnet Temp",
        "cache.item.nextjs":          "Next.js-Cache",
        "cache.item.parcel":          "Parcel-Cache",
        "cache.item.webpack":         "Webpack/Vite-Cache",
        "cache.item.jetbrains":       "JetBrains System-Cache",
        "cache.item.vscode_ws":       "VS Code Workspace-Cache",
        "cache.item.vscode_ext":      "VS Code Erweiterungs-Cache",
        "cache.item.spotify":         "Spotify-Cache",
        "cache.item.discord":         "Discord-Cache",
        "cache.item.teams":           "Teams-Cache",
        "cache.item.zoom":            "Zoom-Cache",
        "cache.item.slack":           "Slack-Cache",
        "cache.item.telegram":        "Telegram-Cache",
        "cache.item.whatsapp":        "WhatsApp-Cache",
        "cache.item.steam_shader":    "Steam Shader-Cache",
        "cache.item.epic":            "Epic Games-Cache",
        "cache.item.gog":             "GOG Galaxy-Cache",
        "cache.item.riot":            "Riot Games-Cache",

        # ── Cache item descriptions ────────────────────────────────────────────
        "cache.desc.win_temp":        "Von Windows und Apps erstellte temporäre Dateien",
        "cache.desc.win_prefetch":    "App-Startcache — beschleunigt den Start, kann aber groß werden",
        "cache.desc.win_wer":         "Absturzdump-Dateien — kann mehrere GB groß sein",
        "cache.desc.win_update":      "Bereits installierte Windows-Updates — sicher zu löschen",
        "cache.desc.win_delivery":    "P2P Windows Update-Übermittlungs-Cache (Administrator erforderlich)",
        "cache.desc.win_dx":          "GPU-Shader-Kompilierungscache — wird automatisch neu erstellt",
        "cache.desc.win_recent":      "Sprungliste / zuletzt geöffnete Dateien",
        "cache.desc.win_thumb":       "Explorer-Miniaturansichten",
        "cache.desc.win_fonts":       "Windows-Schriftartencache — wird automatisch neu erstellt",
        "cache.desc.win_events":      "Systemereignisprotokolldateien (Administrator erforderlich)",
        "cache.desc.win_defender":    "Windows Defender Scanverlauf",
        "cache.desc.win_iis":         "IIS-Webserver-Protokolle (nur wenn IIS installiert ist)",
        "cache.desc.chrome":          "HTTP-Cache + JS-Code-Cache für Google Chrome",
        "cache.desc.chrome_gpu":      "GPU-Shader-Cache für Chrome — wird automatisch neu erstellt",
        "cache.desc.edge":            "HTTP-Cache für Microsoft Edge",
        "cache.desc.edge_webview":    "Eingebetteter Browser-Cache für viele Windows-Apps",
        "cache.desc.firefox":         "HTTP-Cache für alle Firefox-Profile",
        "cache.desc.opera":           "HTTP-Cache für Opera",
        "cache.desc.brave":           "HTTP-Cache für Brave Browser",
        "cache.desc.npm":             "npm-Paket-Cache (~/.npm)",
        "cache.desc.pip":             "pip Wheel/Paket-Cache",
        "cache.desc.gradle":          "Gradle Build-Cache",
        "cache.desc.gradle_wrapper":  "Heruntergeladene Gradle-Distributionen — kann mehrere GB groß sein",
        "cache.desc.maven":           "Lokales Maven-Repository (~/.m2)",
        "cache.desc.yarn":            "Yarn-Paket-Cache",
        "cache.desc.pnpm":            "pnpm Content-Addressable Store",
        "cache.desc.pycache":         "Python Bytecode-Cache-Verzeichnisse (aus Home-Ordner gescannt)",
        "cache.desc.mypy":            "mypy Typprüfungs-Cache-Verzeichnisse",
        "cache.desc.cargo":           "Heruntergeladener Cargo Crate-Cache",
        "cache.desc.docker":          "Docker Image-Layer-Cache — kann viele GB groß sein",
        "cache.desc.android":         "Android-Emulator-Snapshots",
        "cache.desc.nuget":           "NuGet-Paket-Cache — kann 10 GB+ groß sein",
        "cache.desc.composer":        "PHP Composer Paket-Cache",
        "cache.desc.dotnet":          ".NET SDK temporäre Dateien und Tools",
        "cache.desc.nextjs":          ".next/cache-Verzeichnisse (aus Home-Ordner gescannt)",
        "cache.desc.parcel":          ".parcel-cache-Verzeichnisse (aus Home-Ordner gescannt)",
        "cache.desc.webpack":         "node_modules/.cache und .vite-Verzeichnisse",
        "cache.desc.jetbrains":       "IntelliJ / PyCharm / WebStorm etc. Caches",
        "cache.desc.vscode_ws":       "Arbeitsbereichsspezifische Erweiterungsdaten & Cache",
        "cache.desc.vscode_ext":      "Zwischengespeicherte VSIX-Erweiterungsdownloads",
        "cache.desc.spotify":         "Spotify Audio/Bild-Cache — kann mehrere GB groß sein",
        "cache.desc.discord":         "Discord Medien-Cache",
        "cache.desc.teams":           "Microsoft Teams HTTP-Cache und Blob-Speicher",
        "cache.desc.zoom":            "Zoom Meeting-Datencache",
        "cache.desc.slack":           "Slack Medien- und Nachrichten-Cache",
        "cache.desc.telegram":        "Telegram Desktop zwischengespeicherte Medien",
        "cache.desc.whatsapp":        "WhatsApp Desktop-Cache",
        "cache.desc.steam_shader":    "Kompilierte GPU-Shader für Steam-Spiele — bei Bedarf neu erstellt",
        "cache.desc.epic":            "Epic Games Launcher Web-Cache",
        "cache.desc.gog":             "GOG Galaxy Launcher Web-Cache",
        "cache.desc.riot":            "Riot Client Cache (League, Valorant etc.)",

        # ── Virus Scanner tab ─────────────────────────────────────────────────
        "virus.scan_in":          "SCANNEN IN",
        "virus.all_drives":       "Alle Laufwerke",
        "virus.single_file":      "ODER EINZELNE DATEI",
        "virus.btn_browse":       "Datei auswählen…",
        "virus.btn_start":        "Scan starten",
        "virus.btn_stop":         "Stopp",
        "virus.btn_save":         "Bericht speichern",
        "virus.btn_clear":        "Leeren",
        "virus.btn_deepscan":     "Tiefenscan markierter Dateien",
        "virus.auto_deepscan":    "Auto-Tiefenscan nach dem Scan",
        "virus.auto_vt":          "VirusTotal-Prüfung einschließen",
        "virus.auto_vt_hint":     "Kann zusätzliche Zeit in Anspruch nehmen.",
        "virus.auto_vt_no_key":   "Für die automatische Online-Überprüfung wird ein VirusTotal API-Schlüssel benötigt.\n\nBitte zuerst den Schlüssel im Online-Tab eingeben.",
        "virus.btn_verify":       "Online prüfen (VirusTotal)",
        "virus.tab_malicious":    "Bedrohungen",
        "virus.tab_suspicious":   "Verdächtig",
        "virus.tab_online":       "Online",
        "virus.clean_count":      "Sauber: {n}",
        "virus.status_ready":     "Laufwerke oder Datei auswählen und Scan starten drücken.",
        "virus.status_finding":   "Dateien suchen…",
        "virus.status_scanning":  "Scanne {n:,} Datei(en)…",
        "virus.status_complete":  "Scan abgeschlossen — {scanned:,} gescannt · {mal} Bedrohungen · {susp} verdächtig",
        "virus.status_stopped":   "Scan gestoppt — {scanned:,} gescannt",
        "virus.status_threat":    "{name} von {n} Engines als schädlich bestätigt!",
        "virus.col_file":         "Datei",
        "virus.col_score":        "Bewertung",
        "virus.col_finding":      "Hauptfund",
        "virus.col_entropy":      "Entropie",
        "virus.col_verdict":      "VT-Urteil",
        "virus.col_detections":   "Erkennungen",
        "virus.col_engines":      "Engines",
        "virus.col_threat":       "Bedrohungsname",
        "virus.vt_api_label":     "VirusTotal API-Schlüssel:",
        "virus.vt_api_hint":      "Kostenloser Schlüssel auf virustotal.com · 4 Anfragen/Min.",
        "virus.vt_show":          "Anzeigen",
        "virus.vt_hide":          "Verbergen",
        "virus.vt_status_ready":  "API-Schlüssel eingeben und Online prüfen klicken.",
        "virus.vt_complete":      "Online-Überprüfung abgeschlossen — {n} Datei(en) geprüft",
        "virus.vt_waiting":       "Warte {s}s (Free-Tier-Limit)… {done}/{total} fertig",
        "virus.vt_no_key":        "VirusTotal API-Schlüssel im Online-Tab eingeben.",
        "virus.vt_nothing":       "Keine markierten Dateien mit berechneten Hashes. Zuerst einen normalen Scan durchführen.",
        "virus.vt_not_in_db":     "Nicht in DB",
        "virus.vt_error":         "Fehler",
        "virus.deepscan_confirm": "Tiefenscan für {n} markierte Datei(en) durchführen?\n\nSaubere Dateien werden aus den Ergebnissen entfernt.\nJede markierte Datei wird mit vollständiger Entropieanalyse,\nString-Extraktion, PE-Abschnittsanalyse und mehr neu gescannt.",
        "virus.no_key":           "Kein API-Schlüssel",
        "virus.nothing_to_scan":  "Keine Dateien den ausgewählten Filtern entsprechen.",
        "virus.nothing_selected": "Mindestens ein Laufwerk auswählen oder eine Datei angeben.",
        "virus.delete_file":      "Dauerhaft löschen:\n{path}\n\nDies kann nicht rückgängig gemacht werden.",
        "virus.detail_hash":      "SHA-256:   {v}",
        "virus.detail_size":      "Größe:     {v} Bytes",
        "virus.detail_entropy":   "Entropie:  {v} ({label})",
        "virus.detail_hashdb":    "Hash-DB:   {v}",
        "virus.detail_hashdb_hit":"JA — bekannte Bedrohung",
        "virus.detail_hashdb_no": "Kein Treffer",
        "virus.detail_sig":       "Signatur: {status}{signer}",
        "virus.detail_findings":  "── BEFUNDE ──────────────────────────────────────────────",
        "virus.detail_yara":      "── YARA-TREFFER ──────────────────────────────────────────",
        "virus.detail_sections":  "── PE-ABSCHNITTE ─────────────────────────────────────────",
        "virus.detail_open":      "Speicherort öffnen",
        "virus.took":             "⏱ Dauer: {t}",
        "virus.stopped_at":       "⏱ gestoppt nach {t}",
        "virus.elapsed":          "⏱ {t}",
        "virus.time_s":           "s",
        "virus.time_m":           "m",
        "virus.time_h":           "h",
        "virus.status_complete_word": "Scan abgeschlossen",
        "virus.status_stopped_word":  "Scan gestoppt",
        "virus.word_scanned":     "gescannt",
        "virus.word_malicious":   "Bedrohungen",
        "virus.word_suspicious":  "verdächtig",
        "virus.word_processed":   "verarbeitet",

        # ── Settings tab ──────────────────────────────────────────────────────
        "settings.section_virus":    "VIRENSCHUTZ",
        "settings.section_search":   "SUCHE",
        "settings.section_ui":       "OBERFLÄCHE",
        "settings.threads":          "Threads",
        "settings.threads_desc":     "Anzahl paralleler Dateiscans. Mehr = schneller, aber höhere CPU-Auslastung.",
        "settings.skip_media":       "Medien- und Schriftdateien überspringen",
        "settings.skip_media_desc":  ".jpg, .png, .mp4, .ttf etc. überspringen.",
        "settings.exe_only":         "Nur ausführbare Dateien und Skripte",
        "settings.exe_only_desc":    "Nur .exe, .dll, .bat, .ps1, .js etc. scannen.",
        "settings.vt_key":           "VirusTotal API-Schlüssel",
        "settings.vt_key_desc":      "Für Online-Überprüfung. Kostenloser Schlüssel auf virustotal.com",
        "settings.extra_ext":        "Weitere zu überspringende Erweiterungen",
        "settings.extra_ext_desc":   "Eine pro Zeile, mit Punkt.  z.B.  .crp  .pak",
        "settings.extra_dirs":       "Weitere zu überspringende Ordner",
        "settings.extra_dirs_desc":  "Zu überspringende Ordnernamen.  z.B.  Steam  Games",
        "settings.default_mode":     "Standard-Suchmodus",
        "settings.default_mode_desc":"",
        "settings.keyword":          "Stichwort (Teilübereinstimmung)",
        "settings.exact":            "Exakter Name",
        "settings.default_type":     "Standardmäßig suchen nach",
        "settings.default_type_desc":"",
        "settings.default_tab":      "Standard-Tab beim Start",
        "settings.default_tab_desc": "",
        "settings.language":         "Sprache",
        "settings.language_desc":    "App-Sprache. Neustart erforderlich.",
        "settings.btn_save":         "Einstellungen speichern",
        "settings.btn_reset":        "Zurücksetzen",
        "settings.saved":            "✓ Gespeichert — Neustart für Sprachänderung erforderlich",
        "settings.saved_no_restart": "✓ Gespeichert",
        "settings.reset_confirm":    "Alle Einstellungen auf Standardwerte zurücksetzen?",
        "settings.reset_done":       "✓ Auf Standardwerte zurückgesetzt",
        "settings.save_failed":      "config.json konnte nicht geschrieben werden — Berechtigungen prüfen.",

        # ── Common ────────────────────────────────────────────────────────────
        "common.ok":              "OK",
        "common.yes":             "Ja",
        "common.no":              "Nein",
        "common.cancel":          "Abbrechen",
        "common.error":           "Fehler",
        "common.warning":         "Warnung",
        "common.saved":           "Gespeichert",
        "common.confirm_delete":  "Löschen bestätigen",
        "common.perm_denied":     "Zugriff verweigert",
        "common.already_gone":    "Bereits gelöscht",
        "common.open_location":   "Speicherort öffnen",
        "common.copy_path":       "Pfad kopieren",
        "common.copy_name":       "Name kopieren",
        "common.delete":          "Element löschen",
        "common.folder":          "Ordner und ALLE Inhalte",
        "common.file":            "Datei",
        "common.not_responding":  "Reagiert nicht",
    },
}

# Default language
_current = "en"


def set_lang(code: str):
    global _current
    if code in STRINGS:
        _current = code


def t(key: str, **kwargs) -> str:
    """
    Get a translated string by key.
    Supports keyword formatting: t("search.status_results", n=42) → "42 result(s) found"
    Falls back to English if key missing in current language.
    Falls back to the key itself if not found anywhere.
    """
    lang_dict = STRINGS.get(_current, STRINGS["en"])
    text = lang_dict.get(key) or STRINGS["en"].get(key) or key
    if kwargs:
        try:
            text = text.format(**kwargs)
        except (KeyError, ValueError):
            pass
    return text


def available_languages() -> list[tuple[str, str]]:
    """Return list of (code, display_name) tuples."""
    names = {
        "en": "English",
        "de": "Deutsch",
        "ru": "Русский",
    }
    return [(code, names.get(code, code)) for code in STRINGS]